sudo: required
services:
  - docker
before_install:
  - docker build -t elanonimo/docker-frontend -f Dockerfile.dev .
script:
  - docker run elanonimo/docker-frontend yarn run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-774456125926"
  bucket_path: "docker-frontend"    # default bucket_name before first deploy === app name
  on:
    branch: master                  # only deploy when code was pushed to master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
